version: "3.4"
services:
  app1: &app
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: "postgres://postgres:12345678@localhost:5432/postgres"
      # DB_URL: "mongodb://root:12345678@localhost:27017"
      NODE_ENV: production
      HTTP_PORT: 8080
      DB_POOL: 200
    network_mode: host
    depends_on:
      - postgres
      # - mongo
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: "0.6GB"
  app2:
    <<: *app
    ports:
      - 8081:8081
    environment:
      DB_URL: "postgres://postgres:12345678@localhost:5432/postgres"
      DB_POOL: 200
      # DB_URL: "mongodb://root:12345678@localhost:27017"
      NODE_ENV: production
      HTTP_PORT: 8081
      CLUSTER: true
      CLUSTER_WORKERS: 4

  # mongo:
  #   image: mongo
  #   command: --quiet
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 12345678
  #   network_mode: host
  #   ports:
  #     - 27017:27017
  #   # deploy:
  #   #     resources:
  #   #       limits:
  #   #         cpus: "0.4"
  #   #         memory: "1.5GB"
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'client_min_messages=error' -c log_min_messages=FATAL
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    network_mode: host
    volumes:
      - ./database/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: "1.5GB"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    network_mode: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.15"
    #       memory: "0.3GB"
