# @name criar pessoas
POST  http://localhost:8080/pessoas
Content-Type: application/json

{
  "apelido": "silvasds",
  "nome": "joao",
  "nascimento": "2001-01-02",
  "stack": [
    "java",
    "python"
  ]
}

###

# @name get-by-id-pessoas
GET http://localhost:8080/pessoas/6d2c373d-8629-4a23-8eff-9180a1a856e6

###
# @name listar-pessoas-por-nome
GET http://localhost:8080/pessoas?t=joao

###
# @name contagem-pessoas-por-nome
GET http://localhost:8080/contagem-pessoas